// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krngwzarzlsmijndgghc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtybmd3emFyemxzbWlqbmRnZ2hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNTk4ODEsImV4cCI6MjA1ODYzNTg4MX0.P7GpauQW3oDxn8d9sDX3tNBEhCTj7sz6PhrPOOPM9XY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);